resources:
  - ../base

namePrefix: develop-

patches:
  - path: patch-develop.yaml
    target:
      kind: Deployment
      name: spring-cicd-k8s-demo
  - path: namespace.yaml
    target:
      kind: Namespace
