apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-cicd-k8s-demo
spec:
  template:
    spec:
      containers:
        - name: spring-cicd-k8s-demo
          image: whwp4151/spring-cicd-k8s-demo:develop-21
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: develop
