apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cicd-k8s-demo
  namespace: develop
  labels:
    app: spring-cicd-k8s-demo
spec:
  selector:
    matchLabels:
      app: spring-cicd-k8s-demo
  template:
    metadata:
      labels:
        app: spring-cicd-k8s-demo
    spec:
      containers:
        - name: spring-cicd-k8s-demo
          image: whwp4151/spring-cicd-k8s-demo:develop-11
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: develop

---
apiVersion: v1
kind: Service
metadata:
  name: spring-cicd-k8s-demo-service
  namespace: develop
spec:
  type: NodePort
  selector:
    app: spring-cicd-k8s-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30801
