apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-cicd-k8s-demo
spec:
  template:
    spec:
      containers:
        - name: spring-cicd-k8s-demo
          image: whwp4151/spring-cicd-k8s-demo:develop-15
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: develop

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-cicd-k8s-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: develop.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-cicd-k8s-demo-stable
                port:
                  number: 80
