apiVersion: v1
kind: Service
metadata:
  name: spring-cicd-k8s-demo-service
  labels:
    app: spring-cicd-k8s-demo
spec:
  selector:
    app: spring-cicd-k8s-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080
