apiVersion: v1
kind: Service
metadata:
  name: spring-cicd-k8s-demo-service
spec:
  selector:
    app: spring-cicd-k8s-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
